### ISSUE TITLE
Define required and optional nested catch-all semantics

### ISSUE THREAD

**Issue by Amorites** [hannoeru/vite-plugin-pages#273]
### Describe the bug

I have file structure like:

```
├── pages
│   ├── [...all].vue
│   ├── hi
│   │   └── [...all].vue
│   ├── index.vue
│   └── README.md
```

`localhost:5173/hi` is supposed to display `pages/hi/[...all].vue` but display `pages/[...all].vue`

`localhost:5173/hi/` and `localhost:5173/hi/foo` works as expected.

Not really sure this is a bug or feature, but `src/pages/[...all].vue -> /* (/non-existent-page)` described in the doc is a little bit ambiguous.

### Reproduction

https://github.com/Amorites/vite-plugin-pages-all-issue

### System Info

```shell
System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (12) x64 AMD EPYC 7702P 64-Core Processor
    Memory: 18.63 GB / 23.39 GB
    Container: Yes
    Shell: 5.8.1 - /usr/local/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/n/bin/node
    npm: 6.14.4 - /usr/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A please open a GitHub Discussion.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hannoeru** [comment]
fixed in v0.26.0

**Comment by Amorites** [comment]
@hannoer I upgraded the dependency, but the performance is still the same as before

repro: https://github.com/Amorites/vite-plugin-pages-all-issue

**Comment by achaphiv** [comment]
Hmm, after further testing, it seems children are not being sorted with dynamic routes last.

So to fix it, I had to do the following in my `vite.config.ts`

```ts
    Pages({
      routeStyle: 'nuxt',
      onRoutesGenerated(routes: Array<VueRoute>) {
        function isCatchAll(route: VueRoute) {
          return route.name === 'all'
        }

        function isDynamic(route: VueRoute) {
          return route.path.includes(':')
        }

        function fixAll(routes: Array<VueRoute>) {
          routes.sort((a, b) => {
            if (isCatchAll(a)) {
              return 1
            }

            if (isCatchAll(b)) {
              return -1
            }

            const aDynamic = isDynamic(a)
            const bDynamic = isDynamic(b)

            if (aDynamic !== bDynamic) {
              // Non-dynamic first
              return aDynamic ? 1 : -1
            }

            const aSize = a.path.length
            const bSize = b.path.length

            if (aSize !== bSize) {
              // Longest length first
              return bSize - aSize
            }

            return a.path.localeCompare(b.path)
          })

          routes.forEach(fix)
        }

        function fix(route: VueRoute) {
          if (route.children) {
            fixAll(route.children)
          }
        }

        fixAll(routes)
        
        return routes
      },
    })
```

**Comment by hannoeru** [comment]
@achaphiv This is not releated to this issue, please open a new issue and provide a minimal reproduction.

**Comment by hannoeru** [comment]
plan: I confirmed the current behavior on `main`:

- `/hi` matches the root `[...all].vue`;
- `/hi/` and `/hi/foo` match `hi/[...all].vue`.

The Vue resolver currently emits `(.*)*` for a root catch-all and `(.*)` for a nested catch-all. The nested form is intentionally required so that it does not take precedence over an index route.

For v1.0.0, this issue will track a clear required-versus-optional catch-all grammar, tests for index precedence, and matching documentation. We should not silently change `[...all]` until those semantics are defined.
